export default {
  container: {
    width: "100vw",
    height: "100vh",
  },
  header: {
    width: "100%",
    height: "44px",
    backgroundColor: "rgb(0 185 156)",
    top: "0px",
    left: "0px",
    margin: "0 auto",
  },
  headerIcon: {
    width: "38px",
    height: "38px",
    position: "relative",
    margin: "3px",
    cursor: "pointer",
    zIndex: 5,
  },
  logoutImg: {
    width: "38px",
    height: "38px",
    position: "absolute",
    top: "0px",
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingLeft: "1%",
    margin: "3px auto",
    cursor: "pointer",
    zIndex: 5,
  },
  ctime: {
    height: "100%",
    position: "relative",
    top: "0px",
    right: "40px",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    paddingRight: "1%",
    fontSize: "18px",
    color: "#ffffff",
  },
};
